# Separate output-only library: no dependency on WDSP's locks or radio globals.
enable_language(CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
set(PA_BUILD_SHARED_LIBS OFF CACHE BOOL "Static PortAudio inside playback bridge" FORCE)
foreach(feature ASIO DS WMME WDMKS WDMKS_DEVICE_INFO JACK OSS PULSEAUDIO SNDIO SKELETON)
  set(PA_USE_${feature} OFF CACHE BOOL "Unused playback backend" FORCE)
endforeach()
set(PA_BUILD_TESTS OFF CACHE BOOL "No upstream device tests" FORCE)
set(PA_BUILD_EXAMPLES OFF CACHE BOOL "No upstream device examples" FORCE)
set(PA_USE_WASAPI ON CACHE BOOL "Windows shared WASAPI output" FORCE)
if(UNIX AND NOT APPLE)
  find_package(ALSA REQUIRED)
  set(PA_USE_ALSA ON CACHE BOOL "Linux ALSA output" FORCE)
endif()
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/../../Project Files/lib/portaudio-19.7.0" "${CMAKE_BINARY_DIR}/deps/portaudio" EXCLUDE_FROM_ALL)
add_library(thetis_audio SHARED "${CMAKE_CURRENT_LIST_DIR}/../audio/playback.cpp")
target_include_directories(thetis_audio PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../audio")
target_link_libraries(thetis_audio PRIVATE portaudio Threads::Threads)
set_target_properties(thetis_audio PROPERTIES
  LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/stage/$<CONFIG>"
  RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/stage/$<CONFIG>")
if(BUILD_TESTING)
  add_executable(playback_tests "${CMAKE_CURRENT_LIST_DIR}/../tests/playback_tests.cpp")
  target_include_directories(playback_tests PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../audio")
  target_link_libraries(playback_tests PRIVATE thetis_audio Threads::Threads)
  set_target_properties(playback_tests PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/stage/$<CONFIG>")
  add_test(NAME receive_playback_buffer COMMAND playback_tests)
  set_tests_properties(receive_playback_buffer PROPERTIES TIMEOUT 60)
  add_executable(playback_clock_tests "${CMAKE_CURRENT_LIST_DIR}/../tests/playback_clock_tests.cpp")
  target_include_directories(playback_clock_tests PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../audio")
  set_target_properties(playback_clock_tests PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/stage/$<CONFIG>")
  add_test(NAME receive_playback_clocks COMMAND playback_clock_tests)
  set_tests_properties(receive_playback_clocks PROPERTIES TIMEOUT 300)
  add_executable(playback_driver_tests "${CMAKE_CURRENT_LIST_DIR}/../tests/playback_driver_tests.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/../audio/playback.cpp")
  target_include_directories(playback_driver_tests PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../audio"
    "${CMAKE_CURRENT_LIST_DIR}/../../Project Files/lib/portaudio-19.7.0/include")
  target_link_libraries(playback_driver_tests PRIVATE Threads::Threads)
  set_target_properties(playback_driver_tests PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/stage/$<CONFIG>")
  add_test(NAME receive_playback_driver_faults COMMAND playback_driver_tests)
  set_tests_properties(receive_playback_driver_faults PROPERTIES TIMEOUT 60)
endif()
